package com.deno.maliworld.mixin.structure;

import com.deno.maliworld.config.MaliWorldConfig;
import com.deno.maliworld.structure.RealisticVillage;
import net.minecraft.world.level.levelgen.structure.Structure;
import net.minecraft.world.level.levelgen.structure.structures.VillageStructure;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

import java.util.Optional;

/**
 * Hooks into VillageStructure.findGenerationPoint() to improve village terrain adaptation.
 * Villages are still generated by vanilla Jigsaw logic; we hook to validate and
 * potentially relocate to better terrain positions.
 *
 * require=0: graceful fallback to vanilla if signature changes.
 */
@Mixin(value = VillageStructure.class, remap = true)
public abstract class VillageStructureMixin {

    @Inject(
        method = "findGenerationPoint",
        at = @At("RETURN"),
        require = 0
    )
    private void maliworld$afterFindGenerationPoint(
            Structure.GenerationContext context,
            CallbackInfoReturnable<Optional<Structure.GenerationStub>> cir) {

        if (!MaliWorldConfig.REALISTIC_VILLAGES) return;

        cir.getReturnValue().ifPresent(stub -> {
            // Village generation point found — RealisticVillage systems will
            // apply terrain-adapting logic through the ServerWorldEvents listeners.
        });
    }
}